### PR TITLE
Update README.md for installation using package managers

### PR DESCRIPTION
**Pull request by eunos-1128**
Hi, 

Sorry for going without permission, but I have registered the latest version v4.14 on bioconda.

https://anaconda.org/bioconda/reduce

I have updated the README and would be happy to merge it in if you would like.

Regards,

### CODE REVIEW

**Review by russell-taylor — COMMENTED** [review]
When I try to install reduce using conda, it also wants to bring in a number of other repositories (libblast, libboost, libboost-python, libcblas, libgfortran-ng libgfortran5, liplapack, libopenblas, and numpy. None of those should be needed to run reduce, which is a stand-alone C++ program.  Do you know why these are pulled in, and can that be changed?

**Comment by eunos-1128** [comment]
Or libboost-python is needed only on build?

**Comment by russell-taylor** [comment]
I see!

The boost-python is needed only when building Python wrappers for the library, which the C++ program does not need.

**Comment by eunos-1128** [comment]
@russell-taylor 

Building Reduce according to `reduce/CMakeLists.txt` does not require boost-python, does it?

**Comment by eunos-1128** [comment]
I submitted updated one tp [bioconda](https://github.com/bioconda/bioconda-recipes/pull/49721])

**Comment by eunos-1128** [comment]
Reduce on bioconda has been updated.

It has less dependencies because of dropping `libboost-python-devel`.

https://anaconda.org/bioconda/reduce

**Comment by eunos-1128** [comment]
I reduce's formula also to homebrew/linuxbrew formulae.

Now `brew install reduce` is also available.  

https://github.com/brewsci/homebrew-bio/blob/develop/Formula/reduce.rb

**Comment by russell-taylor** [comment]
Thank you for making it easier to get reduce!

**Pull request merged**
